### PR TITLE
 feat: appConfigGet()

### PR DESCRIPTION
**Pull request by svlapin**
Implements fetching App configuration by its id or hostname.

Since that is an endpoint that does not require authentication, allows to instantiate `restClient` without any oAuth-related parameters and gets rid of a constraint that requires `accessToken` to be in token store before sending a request.

### CODE REVIEW

**Comment by svlapin** [comment]
@adieuadieu 
> Is there something we could do to guide the developer?

API will respond with `401` if access token is not provided when it should have been - IMO that's enough.
I was thinking about splitting methods that require authentication and those who do not, but eventually decided we should not store that in the SDK layer. Besides hat - SDK allows to make requests using string URL, where it's generally hard to decide whether access token is needed or not.

> Where will you use the .appConfigGet() method?

App and accounts do regular fetch request to get app config. That was an intent to address that.

**Comment by adieuadieu** [comment]
I'm worried the raw 401 is not good enough. Might be fine for you and I, but perhaps not others. Perhaps we could capture 401s and re-throw them with a nice message?

**Comment by svlapin** [comment]
@adieuadieu thanks for taking time to have a look - addressed in https://github.com/allthings/node-sdk/pull/255/commits/04df605ad8ba189080280654bb5d1344fcefa229

**Comment by svlapin** [comment]
Closing PR for now - apparently there is much effort needed than it seemed. Will get back to that later.

**Pull request closed without merging**
