### PR TITLE
Adding documentation for apiUrl

### PR DESCRIPTION
**Pull request by mosch**
To tell people the behaviour of this.

### CODE REVIEW

**Comment by mosch** [comment]
Ping @adieuadieu looks like the tests are unstable?

**Comment by adieuadieu** [comment]
@mosch No it seems like the failure is legitimate. The tests are run against real Accounts and API (not mocked) and it seems something must have changed or is broken upstream in the API..

**Comment by mosch** [comment]
What's the reason for this? I'd prefer to have fast-running test that reflect if my changes break the behaviour. Now we test the API instead.

**Comment by adieuadieu** [comment]
@mosch mocking the API and it's responses is more work. Testing against the API also let's us catch bugs or changes in the API that may not be reflected in the SDK. Long term, I'd like to have both—especially because it's currently impossible for a public contributor to run the tests against our internal buildkite setup.

**Pull request merged**
