### PR TITLE
fix: make notification email address obligatory while creating an app

### PR DESCRIPTION
**Pull request by egeogretmen**
We have some tests in nisaba using node-sdk that first creates an app to be used in the tests. They were failing because now it is obligatory to provide an email address while creating an app (See https://github.com/allthings/php-prod/commit/65b6d40757a3285379b08d066eab150deb13ef51 ) and node-sdk did not accomodate the changes. This PR makes the node-sdk aware of this change in php-prod and allows the client to provide a notificationsEmailAddress.

Notice: It skips a test that is causing problems ( https://github.com/allthings/node-sdk/blob/b99e12540e40aa38b68db9d353f4af14e1d48f75/src/rest/methods/user.test.ts#L368-L387 ). Since the ALLTHINGS_OAUTH_PASSWORD environment variable is smaller than 32 characters in dev env, the test is not able to change the password back to the original password. This test must be written again.

### CODE REVIEW

**Comment by egeogretmen** [comment]
don't know why the nginx container looks unhealthy in buildkite...
working on replacing the test I skipped in this PR. If I can manage that, I would also include it here (although completely irrelevant to the problem this PR is solving)

**Comment by adashst** [comment]
@egeogretmen I guess adding the region to the environment in the php container in [composer.yml](https://github.com/allthings/node-sdk/blob/master/test/docker-compose.yml#L53-L57) would make it healthy again.
Had this also in other repos.
See f.e. [this PR](https://github.com/allthings/accounts/pull/804)

**Comment by egeogretmen** [comment]
@adashst have fixed it, can you check it again?

**Review by adashst — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
