### PR TITLE
feat: add userChangePassword

### PR DESCRIPTION
**Pull request by TomerRon**
**Update:** This PR now adds `userChangePassword` method.

---

This PR implements a PUT method for the SDK.

I am creating this pull request on behalf of @94argetlam, since he had problems with creating it.

The PUT method is required for `PUT /users/{userId}/password`, which is the only PUT method in our API (not sure why it's not a PATCH). (https://api-doc.allthings.me/#/User%2FPassword/put_users__userId__password)

### CODE REVIEW

**Comment by TomerRon** [comment]
Looks like CI is failing due to test coverage. The other HTTP verbs are covered by the actions that use them, this one is not covered since it's not being used anywhere. I think the best solution would be to implement an actual `userChangePassword` action (and test). Let's see what @svlapin thinks.

**Comment by 94argetlam** [comment]
To be honest I need this as soon as possible.

**Comment by TomerRon** [comment]
> To be honest I need this as soon as possible.

I suggest you use `fetch` for now, and replace it after this is merged :smile:

**Comment by svlapin** [comment]
I agree with @TomerRon - we strive to have a method with a meaningful name for each API endpoint that is used via SDK.
At least the shouldn't be untested code according to the coverage commitment we took in this project.

**Comment by 94argetlam** [comment]
Please, do it as soon as you can, I'll wait and do other stuff. @adieuadieu I'll put change password suff to blocked column until endpoint is done.

**Pull request merged**
